// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: funds.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getFund = `-- name: GetFund :one
SELECT scheme_code, scheme_name, amc, category, inception_date, created_at, updated_at
FROM funds
WHERE scheme_code = $1
`

func (q *Queries) GetFund(ctx context.Context, schemeCode string) (Fund, error) {
	row := q.db.QueryRow(ctx, getFund, schemeCode)
	var i Fund
	err := row.Scan(
		&i.SchemeCode,
		&i.SchemeName,
		&i.Amc,
		&i.Category,
		&i.InceptionDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFunds = `-- name: ListFunds :many
SELECT scheme_code, scheme_name, amc, category, inception_date, created_at, updated_at
FROM funds
WHERE ($1::text IS NULL OR category = $1::text)
  AND ($2::text IS NULL OR amc = $2::text)
ORDER BY scheme_name ASC
`

type ListFundsParams struct {
	Category pgtype.Text `json:"category"`
	Amc      pgtype.Text `json:"amc"`
}

func (q *Queries) ListFunds(ctx context.Context, arg ListFundsParams) ([]Fund, error) {
	rows, err := q.db.Query(ctx, listFunds, arg.Category, arg.Amc)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Fund{}
	for rows.Next() {
		var i Fund
		if err := rows.Scan(
			&i.SchemeCode,
			&i.SchemeName,
			&i.Amc,
			&i.Category,
			&i.InceptionDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFund = `-- name: UpsertFund :exec
INSERT INTO funds (scheme_code, scheme_name, amc, category, inception_date, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
ON CONFLICT (scheme_code) DO UPDATE SET
  scheme_name = EXCLUDED.scheme_name,
  amc = EXCLUDED.amc,
  category = EXCLUDED.category,
  inception_date = EXCLUDED.inception_date,
  updated_at = NOW()
`

type UpsertFundParams struct {
	SchemeCode    string      `json:"scheme_code"`
	SchemeName    string      `json:"scheme_name"`
	Amc           string      `json:"amc"`
	Category      string      `json:"category"`
	InceptionDate pgtype.Date `json:"inception_date"`
}

func (q *Queries) UpsertFund(ctx context.Context, arg UpsertFundParams) error {
	_, err := q.db.Exec(ctx, upsertFund,
		arg.SchemeCode,
		arg.SchemeName,
		arg.Amc,
		arg.Category,
		arg.InceptionDate,
	)
	return err
}
