// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Fund struct {
	SchemeCode    string           `json:"scheme_code"`
	SchemeName    string           `json:"scheme_name"`
	Amc           string           `json:"amc"`
	Category      string           `json:"category"`
	InceptionDate pgtype.Date      `json:"inception_date"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type FundAnalytic struct {
	SchemeCode     string           `json:"scheme_code"`
	Window         string           `json:"window"`
	RollingMin     pgtype.Numeric   `json:"rolling_min"`
	RollingMax     pgtype.Numeric   `json:"rolling_max"`
	RollingMedian  pgtype.Numeric   `json:"rolling_median"`
	RollingP25     pgtype.Numeric   `json:"rolling_p25"`
	RollingP75     pgtype.Numeric   `json:"rolling_p75"`
	MaxDrawdown    pgtype.Numeric   `json:"max_drawdown"`
	CagrMin        pgtype.Numeric   `json:"cagr_min"`
	CagrMax        pgtype.Numeric   `json:"cagr_max"`
	CagrMedian     pgtype.Numeric   `json:"cagr_median"`
	DataStartDate  pgtype.Date      `json:"data_start_date"`
	DataEndDate    pgtype.Date      `json:"data_end_date"`
	NavPoints      pgtype.Int4      `json:"nav_points"`
	RollingPeriods pgtype.Int4      `json:"rolling_periods"`
	ComputedAt     pgtype.Timestamp `json:"computed_at"`
}

type NavHistory struct {
	SchemeCode string           `json:"scheme_code"`
	NavDate    pgtype.Date      `json:"nav_date"`
	NavValue   decimal.Decimal  `json:"nav_value"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type RateLimiterState struct {
	WindowType   string           `json:"window_type"`
	WindowStart  pgtype.Timestamp `json:"window_start"`
	RequestCount int32            `json:"request_count"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type SyncRun struct {
	RunID        pgtype.UUID      `json:"run_id"`
	RunType      string           `json:"run_type"`
	Status       string           `json:"status"`
	StartedAt    pgtype.Timestamp `json:"started_at"`
	FinishedAt   pgtype.Timestamp `json:"finished_at"`
	ErrorSummary pgtype.Text      `json:"error_summary"`
}

type SyncState struct {
	SchemeCode     string           `json:"scheme_code"`
	LastSyncedDate pgtype.Date      `json:"last_synced_date"`
	Status         string           `json:"status"`
	RetryCount     int32            `json:"retry_count"`
	LastError      pgtype.Text      `json:"last_error"`
	LastAttemptAt  pgtype.Timestamp `json:"last_attempt_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}
