// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ClaimNextSyncState(ctx context.Context) (SyncState, error)
	CountSyncStateByStatus(ctx context.Context) ([]CountSyncStateByStatusRow, error)
	CreateSyncRun(ctx context.Context, arg CreateSyncRunParams) error
	FinishSyncRunFailure(ctx context.Context, arg FinishSyncRunFailureParams) error
	FinishSyncRunSuccess(ctx context.Context, runID pgtype.UUID) error
	GetFund(ctx context.Context, schemeCode string) (Fund, error)
	GetFundAnalytics(ctx context.Context, arg GetFundAnalyticsParams) (FundAnalytic, error)
	GetLatestNav(ctx context.Context, schemeCode string) (NavHistory, error)
	GetLatestRunningSyncRun(ctx context.Context) (SyncRun, error)
	GetLatestSyncRun(ctx context.Context) (SyncRun, error)
	GetRateLimiterStateForUpdate(ctx context.Context, windowType string) (RateLimiterState, error)
	InitSyncStateIfMissing(ctx context.Context, schemeCode string) error
	ListFunds(ctx context.Context, arg ListFundsParams) ([]Fund, error)
	ListNavHistoryBetween(ctx context.Context, arg ListNavHistoryBetweenParams) ([]NavHistory, error)
	ListSyncState(ctx context.Context) ([]SyncState, error)
	RankFundsByMaxDrawdown(ctx context.Context, arg RankFundsByMaxDrawdownParams) ([]RankFundsByMaxDrawdownRow, error)
	RankFundsByMedianReturn(ctx context.Context, arg RankFundsByMedianReturnParams) ([]RankFundsByMedianReturnRow, error)
	ResetAllSyncStateToPending(ctx context.Context) error
	UpdateSyncStateAttempt(ctx context.Context, arg UpdateSyncStateAttemptParams) error
	UpdateSyncStateSuccess(ctx context.Context, arg UpdateSyncStateSuccessParams) error
	UpsertFund(ctx context.Context, arg UpsertFundParams) error
	UpsertFundAnalytics(ctx context.Context, arg UpsertFundAnalyticsParams) error
	UpsertNavHistory(ctx context.Context, arg UpsertNavHistoryParams) error
	UpsertRateLimiterState(ctx context.Context, arg UpsertRateLimiterStateParams) error
}

var _ Querier = (*Queries)(nil)
