// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: sync.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimNextSyncState = `-- name: ClaimNextSyncState :one
WITH candidate AS (
  SELECT scheme_code
  FROM sync_state
  WHERE status IN ('PENDING', 'FAILED')
  ORDER BY updated_at ASC
  FOR UPDATE SKIP LOCKED
  LIMIT 1
)
UPDATE sync_state
SET
  status = 'IN_PROGRESS',
  last_attempt_at = NOW(),
  updated_at = NOW()
WHERE scheme_code IN (SELECT scheme_code FROM candidate)
RETURNING scheme_code, last_synced_date, status, retry_count, last_error, last_attempt_at, updated_at
`

func (q *Queries) ClaimNextSyncState(ctx context.Context) (SyncState, error) {
	row := q.db.QueryRow(ctx, claimNextSyncState)
	var i SyncState
	err := row.Scan(
		&i.SchemeCode,
		&i.LastSyncedDate,
		&i.Status,
		&i.RetryCount,
		&i.LastError,
		&i.LastAttemptAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countSyncStateByStatus = `-- name: CountSyncStateByStatus :many
SELECT status, COUNT(*) AS count
FROM sync_state
GROUP BY status
`

type CountSyncStateByStatusRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) CountSyncStateByStatus(ctx context.Context) ([]CountSyncStateByStatusRow, error) {
	rows, err := q.db.Query(ctx, countSyncStateByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountSyncStateByStatusRow{}
	for rows.Next() {
		var i CountSyncStateByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createSyncRun = `-- name: CreateSyncRun :exec
INSERT INTO sync_runs (run_id, run_type, status, started_at)
VALUES ($1, $2, 'RUNNING', NOW())
`

type CreateSyncRunParams struct {
	RunID   pgtype.UUID `json:"run_id"`
	RunType string      `json:"run_type"`
}

func (q *Queries) CreateSyncRun(ctx context.Context, arg CreateSyncRunParams) error {
	_, err := q.db.Exec(ctx, createSyncRun, arg.RunID, arg.RunType)
	return err
}

const finishSyncRunFailure = `-- name: FinishSyncRunFailure :exec
UPDATE sync_runs
SET status = 'FAILED',
    finished_at = NOW(),
    error_summary = $2
WHERE run_id = $1
`

type FinishSyncRunFailureParams struct {
	RunID        pgtype.UUID `json:"run_id"`
	ErrorSummary pgtype.Text `json:"error_summary"`
}

func (q *Queries) FinishSyncRunFailure(ctx context.Context, arg FinishSyncRunFailureParams) error {
	_, err := q.db.Exec(ctx, finishSyncRunFailure, arg.RunID, arg.ErrorSummary)
	return err
}

const finishSyncRunSuccess = `-- name: FinishSyncRunSuccess :exec
UPDATE sync_runs
SET status = 'COMPLETED',
    finished_at = NOW(),
    error_summary = NULL
WHERE run_id = $1
`

func (q *Queries) FinishSyncRunSuccess(ctx context.Context, runID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, finishSyncRunSuccess, runID)
	return err
}

const getLatestRunningSyncRun = `-- name: GetLatestRunningSyncRun :one
SELECT run_id, run_type, status, started_at, finished_at, error_summary
FROM sync_runs
WHERE status = 'RUNNING'
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) GetLatestRunningSyncRun(ctx context.Context) (SyncRun, error) {
	row := q.db.QueryRow(ctx, getLatestRunningSyncRun)
	var i SyncRun
	err := row.Scan(
		&i.RunID,
		&i.RunType,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorSummary,
	)
	return i, err
}

const getLatestSyncRun = `-- name: GetLatestSyncRun :one
SELECT run_id, run_type, status, started_at, finished_at, error_summary
FROM sync_runs
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) GetLatestSyncRun(ctx context.Context) (SyncRun, error) {
	row := q.db.QueryRow(ctx, getLatestSyncRun)
	var i SyncRun
	err := row.Scan(
		&i.RunID,
		&i.RunType,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorSummary,
	)
	return i, err
}

const initSyncStateIfMissing = `-- name: InitSyncStateIfMissing :exec
INSERT INTO sync_state (scheme_code, status, updated_at)
VALUES ($1, 'PENDING', NOW())
ON CONFLICT (scheme_code) DO NOTHING
`

func (q *Queries) InitSyncStateIfMissing(ctx context.Context, schemeCode string) error {
	_, err := q.db.Exec(ctx, initSyncStateIfMissing, schemeCode)
	return err
}

const listSyncState = `-- name: ListSyncState :many
SELECT scheme_code, last_synced_date, status, retry_count, last_error, last_attempt_at, updated_at
FROM sync_state
ORDER BY scheme_code ASC
`

func (q *Queries) ListSyncState(ctx context.Context) ([]SyncState, error) {
	rows, err := q.db.Query(ctx, listSyncState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncState{}
	for rows.Next() {
		var i SyncState
		if err := rows.Scan(
			&i.SchemeCode,
			&i.LastSyncedDate,
			&i.Status,
			&i.RetryCount,
			&i.LastError,
			&i.LastAttemptAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetAllSyncStateToPending = `-- name: ResetAllSyncStateToPending :exec
UPDATE sync_state
SET
  status = 'PENDING',
  updated_at = NOW()
WHERE status <> 'IN_PROGRESS'
`

func (q *Queries) ResetAllSyncStateToPending(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetAllSyncStateToPending)
	return err
}

const updateSyncStateAttempt = `-- name: UpdateSyncStateAttempt :exec
UPDATE sync_state
SET
  status = $2,
  retry_count = $3,
  last_error = $4,
  last_attempt_at = NOW(),
  updated_at = NOW()
WHERE scheme_code = $1
`

type UpdateSyncStateAttemptParams struct {
	SchemeCode string      `json:"scheme_code"`
	Status     string      `json:"status"`
	RetryCount int32       `json:"retry_count"`
	LastError  pgtype.Text `json:"last_error"`
}

func (q *Queries) UpdateSyncStateAttempt(ctx context.Context, arg UpdateSyncStateAttemptParams) error {
	_, err := q.db.Exec(ctx, updateSyncStateAttempt,
		arg.SchemeCode,
		arg.Status,
		arg.RetryCount,
		arg.LastError,
	)
	return err
}

const updateSyncStateSuccess = `-- name: UpdateSyncStateSuccess :exec
UPDATE sync_state
SET
  status = 'COMPLETED',
  last_synced_date = $2,
  retry_count = 0,
  last_error = NULL,
  last_attempt_at = NOW(),
  updated_at = NOW()
WHERE scheme_code = $1
`

type UpdateSyncStateSuccessParams struct {
	SchemeCode     string      `json:"scheme_code"`
	LastSyncedDate pgtype.Date `json:"last_synced_date"`
}

func (q *Queries) UpdateSyncStateSuccess(ctx context.Context, arg UpdateSyncStateSuccessParams) error {
	_, err := q.db.Exec(ctx, updateSyncStateSuccess, arg.SchemeCode, arg.LastSyncedDate)
	return err
}
